keys:
  - &aeneas_alex age1udcr323x2wxg0ywcy3avq4q7gv9qvxrsuvpen6yve5zh9xaa3s0sfmxvcu 
  - &achilles_alex age18tmclsl69g44ck5l4xssa3sm4g8txzua6f74l45ujuyam2vjvqjsz7cqt6
  - &aeneas_workstation age1rsp4hq8qk6qphujv5hksw7wrvh76g4qsyjcukw7x0ux98w6vgpeqle4dmp
  - &achilles_workstation age10p5w4kn9q7svktzthcrrycu4vn8uxek7whlzpx2n6dnyww3rne6ql3cf2t 
  - &maul_server age1l83lpez9nc6t88an0q9s539ql6hd6pv3fj86gag06r8qsdz6asjsh9tcrd 
  - &vader_server age1mk4xprmdy8qljakkxt9p6pdwu8349ng72w9knkprnwy0mdfaeucqzs9dls
  - &phantom_server age1thr6ugzx83lz5r5gwazt05wgudx32xkgm76vdu8d98neg6sxu3xqh2nzkw
  - &atreides_server age15kz7au85c7dyneyz7qlyhxk2cr0m29us9uhprn9fspnc9pe5ga7sp5vq2v
  - &jak_server age1tsh06f74ldhqxst8v0jdks8lvy4e5aqwv3vkjqh8ahf90f207q4stzzg50
  - &saruman_server age1pe850zmzyyu0przt273vv8sqv5pf3g76759hxd4p5rchr4m43vhqqyxetf
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *achilles_workstation
        - *aeneas_workstation 
        - *maul_server
        - *vader_server 
        - *phantom_server
        - *atreides_server
        - *jak_server
        - *saruman_server
  - path_regex: hosts/maul/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *maul_server
  - path_regex: hosts/vader/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *vader_server 
  - path_regex: hosts/phantom/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *phantom_server 
  - path_regex: hosts/atreides/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *atreides_server
  - path_regex: hosts/jak/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *jak_server
  - path_regex: hosts/saruman/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *saruman_server
  - path_regex: hosts/aeneas/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *aeneas_workstation 
  - path_regex: hosts/achilles/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *achilles_workstation
