keys:
  - &aeneas_alex age1n4wj8t0wprvm52jjj8nayrdllk42f5w875uhuvucxj3kz72gffwqen3thq
  - &achilles_alex age18tmclsl69g44ck5l4xssa3sm4g8txzua6f74l45ujuyam2vjvqjsz7cqt6
  - &aeneas_workstation age1tk464uhvajwm45w3c3ck3m4g0mz34tkdss4w8dv2pxn2wfdr7g7qlehcup
  - &achilles_workstation age12y2nly5wyhtkc8nalwh48h8h4cg7r30ly3we7c9esatdmeca5srsklfwuc
  - &maul_server age1g3ksccdsxsw796jlzuyxl93fzg9s3pef8yspxphnsqak75xg8agsleke0g
  - &vader_server age1p28l4v7t2mm4qz3l8a33wkjd2z39esnkyfjpkqhx5737ss9tdgsq9x0m3w 
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *achilles_workstation
        - *aeneas_workstation 
        - *maul_server
        - *vader_server 
  - path_regex: hosts/maul/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *maul_server
  - path_regex: hosts/vader/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *vader_server 
  - path_regex: hosts/aeneas/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *aeneas_workstation 
  - path_regex: hosts/achilles/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *achilles_workstation
