keys:
  - &aeneas_alex age1n4wj8t0wprvm52jjj8nayrdllk42f5w875uhuvucxj3kz72gffwqen3thq
  - &achilles_alex age18tmclsl69g44ck5l4xssa3sm4g8txzua6f74l45ujuyam2vjvqjsz7cqt6
  - &maul_alex age1a7c5ufhxme4kr3jhw53ue2gjjcstzrrr3cclxvu22ks5ulsexa9s5t80uz
  - &maul_server age1g3ksccdsxsw796jlzuyxl93fzg9s3pef8yspxphnsqak75xg8agsleke0g
  - &vader_server age1u9c0etfu5d2wc3z4gyanuq5cwwn0vz0f4eajsk07tkw6l4stzuxqdw8etl
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *maul_alex
        - *maul_server
        - *vader_server 
  - path_regex: hosts/maul/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *maul_alex
        - *maul_server
  - path_regex: hosts/vader/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
        - *vader_server 
  - path_regex: hosts/aeneas/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
  - path_regex: hosts/achilles/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aeneas_alex
        - *achilles_alex
