{ config, pkgs, ... }: {
  wayland.windowManager.hyprland = { 
    enable = true;
    settings = {
      autogenerated = 0;
      "$mod" = "SUPER";
      "$terminal" = "terminator";
      "$fileManager" = "nautilus";
      "$menu" = "wofi --show drun";
      "monitor"="eDP-1,2256x1504,0x0,1";
      "exec-once" = "hyprpaper & sway-audio-idle-inhibit & nm-applet --indicator & blueman-applet & swaync & kanshi";
      "$w1" = ''hyprctl hyprpaper wallpaper "eDP-1,~/Pictures/wp12329536-nixos-wallpapers.png"'';
      bind = [
        # Application launchers
        "$mod, RETURN, exec, $terminal"
        "$mod, W, exec, firefox"
        "$mod, Q, killactive, "
        "$mod, M, exit, "
        "$mod, E, exec, $fileManager"
        "$mod, T, exec, subl"
        "$mod, O, exec, obsidian"
        "$mod, V, togglefloating, "
        "$mod, R, exec, $menu"
        "$mod, L, exec, swaylock -S -c ${config.home.homeDirectory}/.config/swaylock/config"
        "$mod, P, pseudo, # dwindle"
        "$mod, J, togglesplit, # dwindle"
        "$mod, left, movefocus, l"
        "$mod, right, movefocus, r"
        "$mod, up, movefocus, u"
        "$mod, down, movefocus, d"
      ]

      ++ (
        # workspaces
        # binds $mod + [shift +] {1..10} to [move to] workspace {1..10}
        builtins.concatLists (builtins.genList (
            x: let
              ws = let
                c = (x + 1) / 10;
              in
                builtins.toString (x + 1 - (c * 10));
            in [
              "$mod, ${ws}, workspace, ${toString (x + 1)}"
              "CONTROL ALT, right, workspace, ${toString (x + 1)}"
              "$mod SHIFT, ${ws}, movetoworkspace, ${toString (x + 1)}"
            ]
          )
          10)
      );

      bindel = [
      # Media Keys
      ", XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ", XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      ", XF86MonBrightnessDown, exec, brightnessctl set 5%-"
      ", XF86MonBrightnessUp, exec, brightnessctl set +5%"
      #'',switch:Lid Switch ,exec, swaylock -S -c ${config.home.homeDirectory}/.config/swaylock/config ''
      ];

      bindl = [
      # Media Keys
      ", XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ", XF86Search, exec, wofi --show drun"
      ", XF86AudioPlay, exec, playerctl play-pause"
      ", XF86AudioNext, exec, playerctl next "
      ", XF86AudioPrev, exec, playerctl previous"
      ];

      gestures = {
        workspace_swipe = "on";
      };

      input = {
        kb_layout = "us";
        kb_variant = "";
        kb_model = "";
        kb_options = "";
        kb_rules = "";
        follow_mouse = 1;
        touchpad = {
          natural_scroll = "yes";
        };
        sensitivity = 0;
      };

      decoration = {
        rounding = 10;
        blur = {
            enabled = true;
            size = 3;
            passes = 1;
        };
        drop_shadow = "yes";
        shadow_range = 4;
        shadow_render_power = 3;
        "col.shadow" = "rgba(1a1a1aee)";
      };

      general = {
        gaps_in = 5;
        gaps_out = 20;
        border_size = 2;
        "col.active_border" = "rgba(33ccffee) rgba(00ff99ee) 45deg";
        "col.inactive_border" = "rgba(595959aa)";
        layout = "dwindle";
        allow_tearing = false;
      };

      dwindle = {
        pseudotile = "yes";
        preserve_split = "yes";
      };

    };
  };

}
