{
  imports =
    [
      ./acpi_wakeup.nix
      ./android.nix
      ./bluetooth.nix
      ./budgie.nix
      ./cosmic.nix
      ./cups.nix
      ./custom-udev.nix
      ./custom-udev-wakeup.nix
      ./framework-tweaks.nix
      ./game-controllers.nix
      ./gnome.nix
      ./kde.nix
      ./localsend.nix
      ./steam.nix
      ./syncthing.nix
      ./virt-manager.nix
      ./vmware.nix
      ./waydroid.nix
    ];
}
