{
  imports = [
    ./radicale.nix
    ./xonotic.nix
    ./octoprint.nix
    ./jellyfin.nix
    ./laptop-disable-suspend-on-close.nix
    ./remote-backup-server.nix
    ./ollama.nix
    ./immich.nix
    ./qemu-config.nix
    ./blocky.nix
    ./homepage-dashboard.nix
    ./gitea
    ./traefik
    ./tailscale-server.nix
    ./syncthing-server.ni
  ];
}
