{ pkgs, ... }:
{
  home.packages = with pkgs;
  [
    spotify
    bitwarden
    terminator
    guake
    evince
    thunderbird
    nfs-utils
    yubikey-manager
    transmission_4-gtk
    ranger
    vlc
    appimage-run
    wakeonlan
    firefox
    drawing
    rpcs3
    game-devices-udev-rules
    remmina
    google-chrome
    zrok
    calibre
    protonvpn-gui
    watchmate
    minetestclient
    gparted
    rpi-imager
    unetbootin
    isoimagewriter
    ollama
    logseq
    ventoy-full
    jellyfin-media-player
    beeper
    python312Packages.meshtastic
    zoom-us
    # Unstable pkgs
    unstable.awscli2
    unstable.vscode
      dotnetCorePackages.dotnet_9.sdk
      dotnetCorePackages.dotnet_9.runtime
    unstable.terraform
    unstable.hexchat
    unstable.cura-appimage
    unstable.vmware-workstation
    unstable.quickemu
    unstable.signal-desktop
    unstable.hugo
    unstable.xonotic
    unstable.obs-studio
    unstable.godot_4
    unstable.distrobox
    unstable.bolt
    unstable.thunderbolt
    unstable.libreoffice-fresh
    unstable.protonmail-bridge
    unstable.obsidian
    unstable.sublime4
  ];
}
