name: "nix flake check"
on:
  pull_request:
    branches: [ master ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - name: Install Nix
      uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
    - name: Decrypt git-crypt secrets
      run: |
        nix profile install nixpkgs#git-crypt
        echo "${{ secrets.GIT_CRYPT_KEY }}" | base64 -d > /tmp/git-crypt-key
        git-crypt unlock /tmp/git-crypt-key
        rm /tmp/git-crypt-key
    - name: Run flake check
      run: nix flake check --no-build
