name: "nix flake update"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'
jobs:
  lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
    - name: Install Nix
      uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
    - name: Update flake.lock
      id: update
      uses: DeterminateSystems/update-flake-lock@3c4f567004c3b0f7bb85177df020f3825028d2b1 # main
      with:
        token: ${{ secrets.PAT_TOKEN }}
    - name: Enable auto-merge
      if: steps.update.outputs.pull-request-number != ''
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: gh pr merge ${{ steps.update.outputs.pull-request-number }} --auto --merge
